I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dialogues/matematyka.rpy", line 9, in script
    kuba "to dyżurnymi bedą nr 4 i 7"
Exception: Sayer 'kuba' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dialogues/matematyka.rpy", line 9, in script
    kuba "to dyżurnymi bedą nr 4 i 7"
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'kuba' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Staszic The Game 1.0
Tue Mar 26 23:41:01 2024
