I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 63, in script
    monia "luj"
Exception: Sayer 'monia' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 63, in script
    monia "luj"
  File "D:\renpy\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\renpy\renpy-8.2.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy\renpy-8.2.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'monia' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Staszic The Game 1.0
Tue Mar 12 22:06:39 2024
